"""added link to function in fact table

Revision ID: 8de7045f8c04
Revises: b57b43bb5f82
Create Date: 2021-03-03 00:10:34.957911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8de7045f8c04'
down_revision = 'b57b43bb5f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_fact', sa.Column('function_id', postgresql.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_link_fact_function_id_base_function'), 'link_fact', 'base_function', ['function_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_link_fact_function_id_base_function'), 'link_fact', type_='foreignkey')
    op.drop_column('link_fact', 'function_id')
    # ### end Alembic commands ###
