"""added component entities

Revision ID: b57b43bb5f82
Revises: 5405fe777c1f
Create Date: 2021-03-03 00:07:16.669082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b57b43bb5f82'
down_revision = '5405fe777c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('component_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_component')),
    sa.UniqueConstraint('name', name=op.f('uq_component_name'))
    )
    op.create_index(op.f('ix_component_id'), 'component', ['id'], unique=False)
    op.create_table('vehicle',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vehicle_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle')),
    sa.UniqueConstraint('name', name=op.f('uq_vehicle_name'))
    )
    op.create_index(op.f('ix_vehicle_id'), 'vehicle', ['id'], unique=False)
    op.create_table('link_fact',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('vehicle_id', postgresql.UUID(), nullable=False),
    sa.Column('component_id', postgresql.UUID(), nullable=False),
    sa.Column('feature_id', postgresql.UUID(), nullable=False),
    sa.Column('formation_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], name=op.f('fk_link_fact_component_id_component')),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], name=op.f('fk_link_fact_feature_id_feature')),
    sa.ForeignKeyConstraint(['formation_id'], ['formation.id'], name=op.f('fk_link_fact_formation_id_formation')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name=op.f('fk_link_fact_vehicle_id_vehicle')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_link_fact'))
    )
    op.create_index(op.f('ix_link_fact_id'), 'link_fact', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_fact_id'), table_name='link_fact')
    op.drop_table('link_fact')
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_component_id'), table_name='component')
    op.drop_table('component')
    # ### end Alembic commands ###
